baseURL: "/"
languageCode: "en-us"
title: "6307635 - Sea Blue & Sketchy 🌊🔌"
theme: "PaperMod"
relativeURLs: true
canonifyURLs: false

params:
  optimizeImages: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowShareButtons: false
  defaultTheme: auto
  displayFullLangName: true
  description: "Period-correct paint. Period-incorrect everything else."
  mainSections: ["posts", "about"]
  showFeaturedPost: true
  copyrightText: "Theodore Robert Campbell Jr"
  copyrightLink: "https://stupidfoot.com"


services:
  googleAnalytics:
    id: G-DCE0JMJ1G2

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

    - identifier: about
      name: About
      url: /about/
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true