baseURL: "https://6307635.xyz/"
languageCode: "en-us"
title: "Sea Blue & Sketchy 🌊🔌"
theme: "PaperMod"

params:
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  defaultTheme: auto
  displayFullLangName: true
  description: "Period-correct paint. Period-incorrect everything else."

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1

    - identifier: about
      name: About
      url: /about/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true